<a href="https://colab.research.google.com/github/Yash49-Xe/numpy_practice/blob/main/exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
#1
import numpy as np

In [52]:
np.version

<module 'numpy.version' from '/usr/local/lib/python3.12/dist-packages/numpy/version.py'>

In [53]:
#2
np.__version__

'2.0.2'

In [54]:
#2
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc


In [55]:
#3
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [56]:
#4
a = null_vector.dtype
B = ""
A = str(a)
for i in A:
  if i.isdigit():
    B = B + i

bits = int(B)
Bytes = int(bits) / 8

memory = int(null_vector.size *Bytes)
memory

80

In [57]:
#4
null_vector.nbytes

80

In [58]:
#6
nVec = np.zeros(10)
nVec[4] = 1
nVec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [59]:
#7
vec7 = np.arange(10,50)
vec7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [60]:
#8
A = np.arange(10)
#A[::-1]
rev = np.flip(A)
rev

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [61]:
#9
mat_3x3 = np.arange(9)
mat_3x3 = mat_3x3.reshape(3,3)
mat_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
#10
arr = np.array([1,2,0,0,4,0])
ans = []
for i in range(len(arr)):
  if arr[i] != 0:
    ans.append(i)
ans

[0, 1, 4]

In [63]:
#10
arr = np.array([1,2,0,0,4,0])
ans = np.nonzero(arr)[0]
ans

array([0, 1, 4])

In [65]:
#11
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
#12
rng = np.random.default_rng()
randomA = rng.random(size = (3,3,3))
randomA

array([[[0.38744443, 0.68609624, 0.37316482],
        [0.77189411, 0.54834903, 0.09315062],
        [0.56285014, 0.31614764, 0.34324501]],

       [[0.4216427 , 0.64202918, 0.25373401],
        [0.92446032, 0.17217043, 0.91337238],
        [0.43622711, 0.84795718, 0.95961322]],

       [[0.39345402, 0.33818634, 0.41384538],
        [0.65322204, 0.61037386, 0.077787  ],
        [0.47544645, 0.1877784 , 0.82380584]]])

In [68]:
#13
random_10x10 = rng.random(size = (10,10))
maxItem = random_10x10.max()
minItem = random_10x10.min()
[maxItem,minItem]

[np.float64(0.9664602956777558), np.float64(0.005836566890428441)]

In [69]:
#14
ranVec = rng.random(size = 10)
Mean = ranVec.mean()
Mean

np.float64(0.5667506714129379)

In [72]:
#15
row = int(input("Enter the number of rows: "))
col = int(input("Enter the number of columns: "))

if row < 3 or col < 3:
  arr = np.ones((row,col))
else:
  arr = np.ones((row,col))
  arr[1:-1,1:-1] = 0
arr

Enter the number of rows: 7
Enter the number of columns: 8


array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])