<a href="https://colab.research.google.com/github/Yash49-Xe/numpy_practice/blob/main/exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#1
import numpy as np

In [ ]:
np.version

<module 'numpy.version' from '/usr/local/lib/python3.12/dist-packages/numpy/version.py'>

In [ ]:
#2
np.__version__

'2.0.2'

In [ ]:
#2
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc


In [ ]:
#3
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#4
a = null_vector.dtype
B = ""
A = str(a)
for i in A:
  if i.isdigit():
    B = B + i

bits = int(B)
Bytes = int(bits) / 8

memory = int(null_vector.size *Bytes)
memory

80

In [ ]:
#4
null_vector.nbytes

80

In [ ]:
#6
nVec = np.zeros(10)
nVec[4] = 1
nVec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
#7
vec7 = np.arange(10,50)
vec7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
#8
A = np.arange(10)
#A[::-1]
rev = np.flip(A)
rev

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
#9
mat_3x3 = np.arange(9)
mat_3x3 = mat_3x3.reshape(3,3)
mat_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#10
arr = np.array([1,2,0,0,4,0])
ans = []
for i in range(len(arr)):
  if arr[i] != 0:
    ans.append(i)
ans

[0, 1, 4]

In [ ]:
#10
arr = np.array([1,2,0,0,4,0])
ans = np.nonzero(arr)[0]
ans

array([0, 1, 4])

In [ ]:
#11
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#12
rng = np.random.default_rng()
randomA = rng.random(size = (3,3,3))
randomA

array([[[0.58544667, 0.74598918, 0.9741532 ],
        [0.32127279, 0.81730296, 0.07262453],
        [0.25538675, 0.70561345, 0.03663215]],

       [[0.75508077, 0.42985026, 0.71474551],
        [0.17458584, 0.2693173 , 0.23233442],
        [0.5048958 , 0.56669824, 0.06560534]],

       [[0.04971604, 0.94012495, 0.35146051],
        [0.73823596, 0.92775324, 0.91863957],
        [0.11294715, 0.71414508, 0.4660609 ]]])

In [ ]:
#13
random_10x10 = rng.random(size = (10,10))
maxItem = random_10x10.max()
minItem = random_10x10.min()
[maxItem,minItem]

[np.float64(0.9950153641912998), np.float64(0.0036631512311380288)]

In [ ]:
#14
ranVec = rng.random(size = 10)
Mean = ranVec.mean()
Mean

np.float64(0.5148526162885906)

In [ ]:
#15
row = int(input("Enter the number of rows: "))
col = int(input("Enter the number of columns: "))

if row < 3 or col < 3:
  arr = np.ones((row,col))
else:
  arr = np.ones((row,col))
  arr[1:-1,1:-1] = 0
arr

Enter the number of rows: 3
Enter the number of columns: 2


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
#16
original = np.array([[4,5,8],
                     [5,1,9],
                     [6,9,3]])
original

padded_arr = np.pad(original, pad_width = 1, mode = "constant", constant_values = 0)
padded_arr



array([[0, 0, 0, 0, 0],
       [0, 4, 5, 8, 0],
       [0, 5, 1, 9, 0],
       [0, 6, 9, 3, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
#17
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [ ]:
#18
mat_5x5 = np.zeros((5,5))
# mat_5x5

c = 1
for i in range(5):
  for j in range(5):
    if i - j == 1:
      mat_5x5[i][j] = c
      c += 1
mat_5x5

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [ ]:
#18
Mat_5x5 = np.zeros((5,5))

Mat_5x5 = np.diag([1,2,3,4], k = -1)
Mat_5x5

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
#19
mat_8x8 = np.zeros((8,8), dtype = np.int64)
for i in range(8):
  c = i
  for j in range(8):
    if c % 2 == 0:
      mat_8x8[i][j] = 1
    c += 1
mat_8x8

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [ ]:
#19
Mat_8x8 = np.zeros((8,8), dtype = np.int64)

Mat_8x8[1::2, ::2] = 1
Mat_8x8[::2, 1::2] = 1

Mat_8x8

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
#20
np.unravel_index(99, (6,7,8))

(np.int64(1), np.int64(5), np.int64(3))

In [ ]:
#21
checker = np.array([[1,0],
                   [0,1]])

checkerboard = np.tile(checker, (4,4))
checkerboard



array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [ ]:
import numpy as np

In [ ]:
#22
rng = np.random.default_rng()
ranMat = np.random.uniform(4,10,size = (5,5))
# ranMat
maxItem = ranMat.max()
minItem = ranMat.min()

for i in range(5):
  for j in range(5):
    ranMat[i][j] = (ranMat[i][j] - minItem) / (maxItem - minItem)
ranMat


array([[0.16506072, 0.67933468, 0.91213151, 0.22657659, 0.23144768],
       [0.28659565, 0.82471469, 0.27940917, 0.5473683 , 0.20983302],
       [0.39109331, 0.92917855, 0.08345786, 0.56040431, 0.11726577],
       [0.        , 0.41556809, 1.        , 0.744331  , 0.56067825],
       [0.98564516, 0.86151603, 0.79598183, 0.18455999, 0.0250561 ]])

In [ ]:
#24
mat_5x3 = np.arange(1,16)
mat_5x3 = np.reshape(mat_5x3, (5,3))

mat_3x2 = np.arange(16,22)
mat_3x2 = np.reshape(mat_3x2,(3,2))

mat_5x2 = mat_5x3 @ mat_3x2
mat_5x2


array([[112, 118],
       [274, 289],
       [436, 460],
       [598, 631],
       [760, 802]])

In [6]:
#25
aa = np.array([4,7,2,6,8,9,1,5,7,2])
ab = []
for i in range(len(aa)):
  if aa[i] in [4,5,6,7]:
    x = (-1) * aa[i]
  else:
    x = aa[i]
  ab.append(x)
ab = np.array(ab)
ab

array([-4, -7,  2, -6,  8,  9,  1, -5, -7,  2])

In [13]:
#26
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [17]:
#28
np.array(0) / np.array(0)
np.array(0) / np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_13640/3663628848.py:2: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipykernel_13640/3663628848.py:3: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipykernel_13640/3663628848.py:4: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

In [21]:
#30
x = np.arange(7)
y = np.arange(4,14)
z = np.intersect1d(x,y)
z

array([4, 5, 6])

In [22]:
#32
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_13640/3270662262.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

In [28]:
#33
today = np.datetime64('today','D')

yesterday = today - np.timedelta64(1,'D')

tomorrow = today + np.timedelta64(1,'D')

[today,yesterday,tomorrow]

[np.datetime64('2026-04-11'),
 np.datetime64('2026-04-10'),
 np.datetime64('2026-04-12')]

In [30]:
#34
datesJuly = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
datesJuly

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')